dist: trusty
sudo: false

language: node_js
node_js:
  - '13.7.0'

addons:
    chrome: stable
  
cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g @angular/cli
  
script:
  - npm run-script build --prod --base-href $base_href 
  
deploy:
  provider: azure_web_apps
  username: $username
  password: $password
  site: https://bookcrossingfrontend.azurewebsites.net
  edge: true # opt in to dpl v2
  on: production